#!/bin/bash

#MCUNAME=atmega2560
#PROGRAMMER=wiring
MCUNAME=atmega328p
PROGRAMMER=arduino
FILENAME=main
#USBPORT=/dev/ttyACM0
USBPORT=/dev/ttyUSB0

BAUDRATE=9600

#make all 

avrdude -C/etc/avrdude.conf -v -p$MCUNAME -P$USBPORT -c$PROGRAMMER -b$BAUDRATE -D -U flash:w:./$FILENAME.hex:i
