#if USE_TIMERS == 1
	#define TIMER0_COMPA_CUSTOMFUNC_ADDR 1
	#define TIMER0_COMPB_CUSTOMFUNC_ADDR 2
	#define TIMER0_OVF_CUSTOMFUNC_ADDR 3
	
	#define TIMER1_COMPA_CUSTOMFUNC_ADDR 4
	#define TIMER1_COMPB_CUSTOMFUNC_ADDR 5  
	#define TIMER1_OVF_CUSTOMFUNC_ADDR 6
	
	#define TIMER2_COMPA_CUSTOMFUNC_ADDR 7
	#define TIMER2_COMPB_CUSTOMFUNC_ADDR 8
	#define TIMER2_OVF_CUSTOMFUNC_ADDR 9
	
	#define TIMER3_COMPA_CUSTOMFUNC_ADDR 7
	#define TIMER3_COMPB_CUSTOMFUNC_ADDR 8
	#define TIMER3_OVF_CUSTOMFUNC_ADDR 9
	
	#define TIMER4_COMPA_CUSTOMFUNC_ADDR 7
	#define TIMER4_COMPB_CUSTOMFUNC_ADDR 8
	#define TIMER4_OVF_CUSTOMFUNC_ADDR 9
	
	#define TIMER5_COMPA_CUSTOMFUNC_ADDR 7
	#define TIMER5_COMPB_CUSTOMFUNC_ADDR 8
	#define TIMER5_OVF_CUSTOMFUNC_ADDR 9
#endif
