#if USE_TIMERS == 1
	#define TIMER0_COMPA_CUSTOMFUNC_ADDR 1
	#define TIMER0_COMPB_CUSTOMFUNC_ADDR 2
	#define TIMER0_OVF_CUSTOMFUNC_ADDR 3
	#define TIMER1_COMPA_CUSTOMFUNC_ADDR 4
	#define TIMER1_COMPB_CUSTOMFUNC_ADDR 5  
	#define TIMER1_OVF_CUSTOMFUNC_ADDR 6
	#define TIMER2_COMPA_CUSTOMFUNC_ADDR 7
	#define TIMER2_COMPB_CUSTOMFUNC_ADDR 8
	#define TIMER2_OVF_CUSTOMFUNC_ADDR 9
#endif
